server:
  port: 8081
spring:
  application:
    name: SERVICE-CLIENT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clientdb?createDatabaseIfNotExist=true
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-timeout: 5s
        hostname: 192.168.1.25
eureka:
  client:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
    web.base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
