server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service-client
          uri: lb://SERVICE-CLIENT
          predicates:
            - Path=/clients/**
        - id: service-car
          uri: lb://SERVICE-CAR
          predicates:
            - Path=/cars/**
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 30s
        health-check-timeout: 10s
        hostname: 192.168.1.25

eureka:
  client:
    enabled: false # Set to `true` only if you are still using Eureka
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
    web.base-path: /actuator
  endpoint:
    prometheus:
        enabled: true

  metrics:
    export:
      prometheus:
        enabled: true

